dist: trusty
sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8
    
before_script:
  - docker pull guigolab/chip-nf@sha256:f912436e8791a9d1f9cadf76099f760151435a43d7873712ee692cb2b0f8947e
  - curl -fsSL get.nextflow.io | bash && mv nextflow $HOME/bin

script:
  - ./ci run -profile circleci && ./ci validate
    